# Generated by Django 3.2.7 on 2021-09-16 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocxTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichn', models.CharField(max_length=10)),
                ('docxtemplate', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Gemeinde',
            fields=[
                ('gemeindenummer', models.IntegerField(primary_key=True, serialize=False)),
                ('koerperschaft', models.TextField(max_length=50)),
                ('koerperschaft_ort', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='LiqKreditentwicklung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haushaltsjahr', models.IntegerField()),
                ('gemeinde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hhapp.gemeinde')),
            ],
        ),
        migrations.CreateModel(
            name='InvestKreditentwicklung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haushaltsjahr', models.IntegerField()),
                ('anfangsbestand', models.DecimalField(decimal_places=2, max_digits=11)),
                ('aufnahme', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tilgung', models.DecimalField(decimal_places=2, max_digits=11)),
                ('gemeinde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hhapp.gemeinde')),
            ],
        ),
        migrations.CreateModel(
            name='Investitionsentwicklung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haushaltsjahr', models.IntegerField()),
                ('gemeinde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hhapp.gemeinde')),
            ],
        ),
        migrations.CreateModel(
            name='Haushalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haushaltsjahr', models.IntegerField()),
                ('nachtragshaushalt', models.BooleanField(default=False)),
                ('nachtragsnummer', models.IntegerField(blank=True)),
                ('veroeffbuergbet', models.DateTimeField(blank=True)),
                ('beschluss', models.DateTimeField(blank=True)),
                ('genehmigung', models.DateTimeField(blank=True)),
                ('veroeffhh', models.DateTimeField(blank=True)),
                ('angelegt', models.DateTimeField(auto_now_add=True)),
                ('doppelhaushalt', models.BooleanField(default=False)),
                ('docxtemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hhapp.docxtemplates')),
                ('gemeinde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hhapp.gemeinde')),
            ],
        ),
        migrations.CreateModel(
            name='Finanzentwicklung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haushaltsjahr', models.IntegerField()),
                ('jahreserg', models.DecimalField(decimal_places=2, max_digits=11)),
                ('gemeinde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hhapp.gemeinde')),
            ],
        ),
        migrations.CreateModel(
            name='Ergebnisentwicklung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haushaltsjahr', models.IntegerField()),
                ('gemeinde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hhapp.gemeinde')),
            ],
        ),
        migrations.CreateModel(
            name='Eigenkapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haushaltsjahr', models.IntegerField()),
                ('anfangsbestand', models.DecimalField(decimal_places=2, max_digits=11)),
                ('veraend', models.DecimalField(decimal_places=2, max_digits=11)),
                ('gemeinde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hhapp.gemeinde')),
            ],
        ),
        migrations.AddField(
            model_name='docxtemplates',
            name='gemeinde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hhapp.gemeinde'),
        ),
    ]
