# Generated by Django 3.2.7 on 2021-09-26 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Koerperschaften',
            fields=[
                ('koerperschaft', models.TextField(max_length=150, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='eigenkapital',
            name='anfangsbestand',
        ),
        migrations.RemoveField(
            model_name='eigenkapital',
            name='gemeinde',
        ),
        migrations.RemoveField(
            model_name='eigenkapital',
            name='haushaltsjahr',
        ),
        migrations.RemoveField(
            model_name='eigenkapital',
            name='veraend',
        ),
        migrations.AlterField(
            model_name='gemeinde',
            name='gemeindenummer',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemeinde',
            name='koerperschaft_ort',
            field=models.TextField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='gemeinde',
            name='koerperschaft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hhapp.koerperschaften'),
        ),
    ]
