# Generated by Django 3.2.7 on 2021-09-26 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhapp', '0002_auto_20210926_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='eigenkapital',
            name='anfangsbestand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='eigenkapital',
            name='gemeinde',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hhapp.gemeinde'),
        ),
        migrations.AddField(
            model_name='eigenkapital',
            name='haushaltsjahr',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eigenkapital',
            name='veraend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gemeinde',
            name='koerperschaft_ort',
            field=models.TextField(max_length=150),
        ),
    ]
