# Generated by Django 3.2.7 on 2021-09-26 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhapp', '0003_auto_20210926_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haushalt',
            name='docxtemplate',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hhapp.docxtemplates'),
        ),
    ]
