# Generated by Django 3.2.7 on 2021-09-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhapp', '0004_alter_haushalt_docxtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haushalt',
            name='nachtragsnummer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
