# Generated by Django 3.2.7 on 2021-09-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhapp', '0005_alter_haushalt_nachtragsnummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haushalt',
            name='beschluss',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='haushalt',
            name='genehmigung',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='haushalt',
            name='veroeffbuergbet',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='haushalt',
            name='veroeffhh',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
