# Generated by Django 3.2.7 on 2021-10-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhapp', '0009_auto_20211017_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafiles',
            name='datafilebez',
            field=models.CharField(default='testdf', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datafiles',
            name='datafile',
            field=models.FileField(upload_to='hh/data'),
        ),
    ]
