# Generated by Django 3.2.7 on 2021-11-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhapp', '0012_auto_20211105_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='ergebnisentwicklung',
            name='ergao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ergebnisentwicklung',
            name='ergfin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ergebnisentwicklung',
            name='ergvw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liqkreditentwicklung',
            name='anfangsbestand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liqkreditentwicklung',
            name='aufnahme',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liqkreditentwicklung',
            name='tilgung',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
    ]
